# Generated by Django 3.1.7 on 2021-03-15 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='sum of the cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
