# Generated by Django 3.1.7 on 2021-03-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0002_auto_20210308_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='gender'),
        ),
    ]
