# Generated by Django 3.1.7 on 2021-03-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0005_auto_20210308_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottombanners',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.productcategory'),
        ),
    ]
