# Generated by Django 3.2.6 on 2021-08-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0008_auto_20210322_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='main banner on index page')),
                ('main_text', models.TextField(blank=True, verbose_name='text on main banner')),
                ('image', models.ImageField(blank=True, upload_to='banner_images', verbose_name='banner image')),
            ],
        ),
    ]
