# Generated by Django 3.2.6 on 2021-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0009_mainbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='name',
            field=models.CharField(max_length=258, unique=True, verbose_name='main banner on index page'),
        ),
    ]
